### ISSUE TITLE
crash on nougat

### ISSUE THREAD

**Issue by youling257** [chylek/FakeWifi#1]
crash on nougat，stopped work，can't open it.

**Comment by youling257** [comment]
09-19 14:57:17.821  2541  3063 W Process : Unable to open /proc/6536/status
09-19 14:57:17.821  2541  3063 V Prevent : pid 6536 is not for eu.chylek.adam.fakewifi
09-19 14:57:17.821  2541  3063 D Prevent : action: app died, package: eu.chylek.adam.fakewifi, count: 0
09-19 14:57:17.844  3641  3641 I DOZE    : launcherPkgs0====com.google.android.apps.nexuslauncher  com.google.android.apps.nexuslauncher.NexusLauncherActivity
09-19 14:57:17.857  2541  3919 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@6eb9790 attribute=null, token = android.os.BinderProxy@154bca
09-19 14:57:18.282  3641  3641 I DOZE    : launcherPkgs0====com.google.android.apps.nexuslauncher  com.google.android.apps.nexuslauncher.NexusLauncherActivity
09-19 14:57:18.283  2541  5096 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=eu.chylek.adam.fakewifi/.MainActivity bnds=[1527,449][1906,629]} from uid 10132 on display 0
09-19 14:57:18.290  2541  5096 V Prevent : leaving, current: com.google.android.apps.nexuslauncher
09-19 14:57:18.296  2541  5096 D Prevent : action: user leaving activity, package: com.google.android.apps.nexuslauncher, count: 1
09-19 14:57:18.310  2541  3918 D Prevent : allow start activity eu.chylek.adam.fakewifi/.MainActivity
09-19 14:57:18.322  2541  3918 I ActivityManager: Start proc 6577:eu.chylek.adam.fakewifi/u0a225 for activity eu.chylek.adam.fakewifi/.MainActivity
09-19 14:57:18.325  6577  6577 W art     : Unexpected CPU variant for X86 using defaults: x86
09-19 14:57:18.332  2541  3918 D Prevent : allow start activity eu.chylek.adam.fakewifi/.MainActivity
09-19 14:57:18.342  2541  5096 V Prevent : launch, current: eu.chylek.adam.fakewifi
09-19 14:57:18.343  2541  5096 D Prevent : action: start activity, package: eu.chylek.adam.fakewifi, count: 1
09-19 14:57:18.348  6577  6577 W System  : ClassLoader referenced unknown path: /data/app/eu.chylek.adam.fakewifi-1/lib/x86
09-19 14:57:18.350  6577  6577 W art     : JIT profile information will not be recorded: profile file does not exits.
09-19 14:57:18.383  3407  3814 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
09-19 14:57:18.441  6577  6577 E Xposed  : java.lang.NoSuchMethodError: android.content.res.ResourcesKey(java.lang.String,java.lang.Integer,null,java.lang.Float)#bestmatch
09-19 14:57:18.441  6577  6577 E Xposed  : 	at de.robv.android.xposed.XposedHelpers.findConstructorBestMatch(XposedHelpers.java:672)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at de.robv.android.xposed.XposedHelpers.findConstructorBestMatch(XposedHelpers.java:685)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at de.robv.android.xposed.XposedHelpers.newInstance(XposedHelpers.java:1324)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at android.app.AndroidAppHelper.createResourcesKey(AndroidAppHelper.java:77)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at android.app.AndroidAppHelper.addActiveResource(AndroidAppHelper.java:109)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at android.content.res.XModuleResources.createInstance(XModuleResources.java:44)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at com.zst.xposed.xuimod.mods.ToastAnimationMod.handleLoadPackage(ToastAnimationMod.java:64)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at com.zst.xposed.xuimod.XuiMod.handleLoadPackage(XuiMod.java:65)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:116)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at android.app.ActivityThread.handleBindApplication(Unknown Source)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at android.os.Looper.loop(Looper.java:154)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at java.lang.reflect.Method.invoke(Native Method)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
09-19 14:57:18.441  6577  6577 E Xposed  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-19 14:57:18.446  6577  6577 I Xposed  : processName:eu.chylek.adam.fakewifi  packageName:eu.chylek.adam.fakewifi
09-19 14:57:18.464  6577  6577 D log_2   : 对话框取消已激活
09-19 14:57:18.465  6577  6577 D log_2   : class未发现:java.lang.ClassNotFoundException: android.support.v7.app.AlertDialog.Builder
09-19 14:57:18.465  6577  6577 D log_2   : clazz未知
09-19 14:57:18.470  6577  6577 D log_2   : 增强功能已开启！
09-19 14:57:18.568  6577  6577 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-19 14:57:18.771  3569  4455 D LogHelper: Google Analytics log entry: {&cd3=android_x86, &t=appview, &cd1=userdebug, &cd5=7.1.2-2b9090bdd8, &an=eu.chylek.adam.fakewifi, &cd=eu.chylek.adam.fakewifi.MainActivity, &cd4=Pixel XL, &cd13=240, &cd12=1920 * 1200 60Hz}
09-19 14:57:18.787  6577  6577 D AndroidRuntime: Shutting down VM
09-19 14:57:18.788  6577  6577 E AndroidRuntime: FATAL EXCEPTION: main


09-19 14:57:18.788  6577  6577 E AndroidRuntime: Process: eu.chylek.adam.fakewifi, PID: 6577
09-19 14:57:18.788  6577  6577 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.chylek.adam.fakewifi/eu.chylek.adam.fakewifi.MainActivity}: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.ContextImpl.checkMode(ContextImpl.java:2134)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:354)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:349)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at eu.chylek.adam.fakewifi.MainFragment.init(MainFragment.java:45)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at eu.chylek.adam.fakewifi.MainFragment.onCreateView(MainFragment.java:90)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6711)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
09-19 14:57:18.788  6577  6577 E AndroidRuntime: 	... 10 more
09-19 14:57:18.792  3569  4455 D LogHelper: Google Analytics log entry: {&exf=1, &cd3=android_x86, &t=exception, &cd1=userdebug, &cd5=7.1.2-2b9090bdd8, &exd=java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.chylek.adam.fakewifi/eu.chylek.adam.fakewifi.MainActivity}: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.os.Looper.loop(Looper.java:154)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at java.lang.reflect.Method.invoke(Native Method)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-19 14:57:18.792  3569  4455 D LogHelper: Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.ContextImpl.checkMode(ContextImpl.java:2134)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:354)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:349)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at eu.chylek.adam.fakewifi.MainFragment.init(MainFragment.java:45)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at eu.chylek.adam.fakewifi.MainFragment.onCreateView(MainFragment.java:90)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.Activity.performStart(Activity.java:6711)
09-19 14:57:18.792  3569  4455 D LogHelper: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
09-19 14:57:18.792  3569  4455 D LogHelper: 	... 10 more
09-19 14:57:18.792  3569  4455 D LogHelper: , &an=eu.chylek.adam.fakewifi, &cd4=Pixel XL, &cd13=240, &cd12=1920 * 1200 60Hz}
09-19 14:57:18.793  2541  5096 W ActivityManager:   Force finishing activity eu.chylek.adam.fakewifi/.MainActivity
09-19 14:57:18.798  6577  6577 I Process : Sending signal. PID: 6577 SIG: 9
09-19 14:57:18.826  2541  2541 V Prevent : pid: 4018, package: android, process: system:ui
09-19 14:57:18.826  2541  2541 V Prevent : disallow broadcast com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver, sender: android
09-19 14:57:18.848  2541  2541 V Prevent : pid: 4018, package: android, process: system:ui
09-19 14:57:18.848  2541  2541 V Prevent : disallow broadcast com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver, sender: android
09-19 14:57:18.848  2541  3918 I ActivityManager: Process eu.chylek.adam.fakewifi (pid 6577) has died
09-19 14:57:18.848  2541  3918 D ActivityManager: cleanUpApplicationRecord -- 6577
09-19 14:57:18.858  2541  3918 V Prevent : resume, current: com.google.android.apps.nexuslauncher
09-19 14:57:18.864  2541  3918 D Prevent : action: resume activity, package: com.google.android.apps.nexuslauncher, count: 1
09-19 14:57:18.868  2541  3918 W Process : Unable to open /proc/6577/status
09-19 14:57:18.869  2541  3918 V Prevent : pid 6577 is not for eu.chylek.adam.fakewifi
09-19 14:57:18.869  2541  3918 D Prevent : action: app died, package: eu.chylek.adam.fakewifi, count: 0

**Comment by chylek** [comment]
Thanks for the report and sorry for the inconvenience. 
I didn't test on Android 7 and it looks like it no longer allows preferences to be MODE_WORLD_READABLE and that makes things more complicated. 
Working on a fix.

**Comment by youling257** [comment]
Change MODE_WORLD_READABLE to MODE_PRIVATE

**Comment by chylek** [comment]
The Xposed part can't access MODE_PRIVATE preferences.

**Comment by chylek** [comment]
Ok, I think I found a solution (6da81a4). I can't test Xposed on Android 7, but at least I am able to open the app
