### ISSUE TITLE
Can it work for apps which search for WiFi devices (like iRobot HOME)?

### ISSUE THREAD

**Issue by lwcorp** [chylek/FakeWifi#15]
The [iRobot HOME](https://play.google.com/store/apps/details?id=com.irobot.home) app provides remote control over your WiFi connected iRobot device.

When installing the app for the first time, you can't complete the installation unless it finds your device in your WiFi.

Should FakeWiFi be able to trick it to connect anyway? Assuming, of course, I shall define the real SSID to which the device is connected.

**Comment by chylek** [comment]
No. The app would need to emulate the responses that the iRobot device gives and that is not its purpose.

**Comment by lwcorp** [comment]
Is it possible you closed it too quickly? I had no intention to emulate the response.
The device is indeed on that network, but this network isn't treated like a Wi-Fi due to being used within a virtual machine (which treats the Wi-Fi like 3g).

**Comment by chylek** [comment]
I don't understand your issue then. You want me to say if the app works with iRobot Home? I don't know. I can't test the app for you. Try it and you'll see, it's free and rather easy. If it doesn't work, you can create a new issue, but I don't have time to fix them, so you'll have to either create a fix and pull request or wait until somebody else does it.

**Comment by lwcorp** [comment]
No, I want to know if the app can provide access into network devices. Think about Chromecast if it's easier.
In case of Ethernet but no Wi-Fi, can the app be used to let another app access a network device.
