### ISSUE TITLE
FakeWifi with WiFi Calling?

### ISSUE THREAD

**Issue by stix78** [chylek/FakeWifi#6]
First and most importantly, thanks so much for your hard work on this module! With a few reboots and guessed MAC addresses I have everything up and running on my Nougat flavor Samsung A3 as proved by Test Wifi.

However...I was really hoping this might allow me to make use of the now popular "Wifi Calling" feature, but over Ethernet. Do you know if this is, or could be possible?

So far all attempts are unrecognised by the phone dialer, and the Wifi Calling icon disappears as soon as Ethernet is plugged in - just as it does without your module installed. "Main switch" and "Select all" are both active. Huge thanks!

**Comment by chylek** [comment]
It certainly isn't popular in my country, as I've never heard of it :) Either my phones don't support it or the service isn't offered by my providers. I'm afraid I won't be able to help you. It looks like it's not managed by any standalone app but by the system itself, which means that substantial changes would be needed and I can't make them if I don't have the service. Sorry.

**Comment by stix78** [comment]
That's fair enough, and you're right I have only seen reference to the service in the UK & US. Perhaps I'll be back in touch if ever it becomes more widely used! Thanks for your help.
